export default {
	name: "plugins-workspace",
	displayName: "Plugins",
	repoUrl: "https://github.com/tauri-apps/plugins-workspace/tree/v2",
	packages: [
		{
			name: "authenticator",
			path: "plugins/authenticator",
			description:
				"Authenticate users through platform-specific credential managers.",
			cargo: "https://crates.io/crates/tauri-plugin-authenticator",
			npm: "https://www.npmjs.com/package/@tauri-apps/plugin-authenticator",
		},
		{
			name: "autostart",
			path: "plugins/autostart",
			description: "Register your app to run on startup.",
			cargo: "https://crates.io/crates/tauri-plugin-autostart",
			npm: "https://www.npmjs.com/package/@tauri-apps/plugin-autostart",
		},
		{
			name: "barcode-scanner",
			path: "plugins/barcode-scanner",
			description: "Scan barcodes and QR codes.",
			cargo: "https://crates.io/crates/tauri-plugin-barcode-scanner",
			npm: "https://www.npmjs.com/package/@tauri-apps/plugin-barcode-scanner",
		},
		{
			name: "biometric",
			path: "plugins/biometric",
			description: "Authenticate users with biometrics.",
			cargo: "https://crates.io/crates/tauri-plugin-biometric",
			npm: "https://www.npmjs.com/package/@tauri-apps/plugin-biometric",
		},
		{
			name: "clipboard-manager",
			path: "plugins/clipboard-manager",
			description: "Manage the system clipboard.",
			cargo: "https://crates.io/crates/tauri-plugin-clipboard-manager",
			npm: "https://www.npmjs.com/package/@tauri-apps/plugin-clipboard-manager",
		},
		{
			name: "deep-link",
			path: "plugins/deep-link",
			description: "Open your app through a custom URL scheme.",
			cargo: "https://crates.io/crates/tauri-plugin-deep-link",
			npm: "https://www.npmjs.com/package/@tauri-apps/plugin-deep-link",
		},
		{
			name: "dialog",
			path: "plugins/dialog",
			description: "Native dialogs for your app.",
			cargo: "https://crates.io/crates/tauri-plugin-dialog",
			npm: "https://www.npmjs.com/package/@tauri-apps/plugin-dialog",
		},
		{
			name: "fs",
			path: "plugins/fs",
			description: "Modern and easy-to-use file system API.",
			cargo: "https://crates.io/crates/tauri-plugin-fs",
			npm: "https://www.npmjs.com/package/@tauri-apps/plugin-fs",
		},
		{
			name: "global-shortcut",
			path: "plugins/global-shortcut",
			description: "Register global shortcuts for your app.",
			cargo: "https://crates.io/crates/tauri-plugin-global-shortcut",
			npm: "https://www.npmjs.com/package/@tauri-apps/plugin-global-shortcut",
		},
		{
			name: "http",
			path: "plugins/http",
			description: "Make HTTP requests from your app.",
			cargo: "https://crates.io/crates/tauri-plugin-http",
			npm: "https://www.npmjs.com/package/@tauri-apps/plugin-http",
		},
		{
			name: "log",
			path: "plugins/log",
			description: "Configurable logging for your app.",
			cargo: "https://crates.io/crates/tauri-plugin-log",
			npm: "https://www.npmjs.com/package/@tauri-apps/plugin-log",
		},
		{
			name: "nfc",
			path: "plugins/nfc",
			description: "Read and write NFC tags.",
			cargo: "https://crates.io/crates/tauri-plugin-nfc",
			npm: "https://www.npmjs.com/package/@tauri-apps/plugin-nfc",
		},
		{
			name: "notification",
			path: "plugins/notification",
			description: "Send native notifications from your app.",
			cargo: "https://crates.io/crates/tauri-plugin-notification",
			npm: "https://www.npmjs.com/package/@tauri-apps/plugin-notification",
		},
		{
			name: "os",
			path: "plugins/os",
			description: "Access operating system-specific information.",
			cargo: "https://crates.io/crates/tauri-plugin-os",
			npm: "https://www.npmjs.com/package/@tauri-apps/plugin-os",
		},
		{
			name: "positioner",
			path: "plugins/positioner",
			description: "Move and resize your app's windows.",
			cargo: "https://crates.io/crates/tauri-plugin-positioner",
			npm: "https://www.npmjs.com/package/@tauri-apps/plugin-positioner",
		},
		{
			name: "process",
			path: "plugins/process",
			description: "Manage child processes.",
			cargo: "https://crates.io/crates/tauri-plugin-process",
			npm: "https://www.npmjs.com/package/@tauri-apps/plugin-process",
		},
		{
			name: "shell",
			path: "plugins/shell",
			description: "Open external programs and URLs.",
			cargo: "https://crates.io/crates/tauri-plugin-shell",
			npm: "https://www.npmjs.com/package/@tauri-apps/plugin-shell",
		},
		{
			name: "sql",
			path: "plugins/sql",
			description: "Connect to and manage SQL databases.",
			cargo: "https://crates.io/crates/tauri-plugin-sql",
			npm: "https://www.npmjs.com/package/@tauri-apps/plugin-sql",
		},
		{
			name: "store",
			path: "plugins/store",
			description: "Persistent key-value storage for your app.",
			cargo: "https://crates.io/crates/tauri-plugin-store",
			npm: "https://www.npmjs.com/package/@tauri-apps/plugin-store",
		},
		{
			name: "stronghold",
			path: "plugins/stronghold",
			description: "Securely store sensitive data.",
			cargo: "https://crates.io/crates/tauri-plugin-stronghold",
			npm: "https://www.npmjs.com/package/@tauri-apps/plugin-stronghold",
		},
		{
			name: "updater",
			path: "plugins/updater",
			description: "Update your app from a remote server.",
			cargo: "https://crates.io/crates/tauri-plugin-updater",
			npm: "https://www.npmjs.com/package/@tauri-apps/plugin-updater",
		},
		{
			name: "upload",
			path: "plugins/upload",
			description: "Upload files to a remote server.",
			cargo: "https://crates.io/crates/tauri-plugin-upload",
			npm: "https://www.npmjs.com/package/@tauri-apps/plugin-upload",
		},

		{
			name: "websocket",
			path: "plugins/websocket",
			description: "Connect to and manage WebSocket connections.",
			cargo: "https://crates.io/crates/tauri-plugin-websocket",
			npm: "https://www.npmjs.com/package/@tauri-apps/plugin-websocket",
		},
		{
			name: "window-state",
			path: "plugins/window-state",
			description: "Save and restore window state.",
			cargo: "https://crates.io/crates/tauri-plugin-window-state",
			npm: "https://www.npmjs.com/package/@tauri-apps/plugin-window-state",
		},
	],
};
