name: Deploy VitePress Docs

on:
  push:
    branches:
      - main

      # todo: cache pnpm: build releases and somehow use it in the docs build

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: pnpm
        run: npm install -g pnpm

      - name: dependencies
        run: pnpm install

      - name: releases
        run: pnpm build:releases

      - name: VitePress
        run: pnpm run docs:build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src/.vitepress/dist